[[redirects]]
  from = "/api/*"
  to = "https://conversational-rag-customer-support.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
